# Generated by Django 5.2.13 on 2026-04-21 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_response_flow_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='question_logic',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='logic',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
