# Generated by Django 5.2.13 on 2026-04-21 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_answer_question_logic_question_logic'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='question_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
